[project]
site_name = "M1nu0x0"
site_description = "Dev Logs"
site_author = "M1nu0x0"
site_url = "https://m1nu0x0.github.io/"

repo_url = "https://github.com/m1nu0x0/m1nu0x0.github.io"
repo_name = "M1nu0x0/M1nu0x0.github.io"

edit_uri = "https://raw.githubusercontent.com/m1nu0x0/m1nu0x0.github.io/main/docs/"

copyright = """
Copyright &copy; 2026 The authors
"""

#extra_css = ["stylesheets/extra.css"]
#extra_javascript = ["javascripts/extra.js"]

[project.theme]

name = "material"
custom_dir = "overrides"
favicon = "assets/Avatar 35999676.png"
logo = "assets/Avatar 35999676.png"
language = "en"

features = [
    "announce.dismiss",

    #"content.action.edit",
    "content.action.view",

    "content.code.annotate",
    "content.code.copy",
    "content.code.select",

    "content.footnote.tooltips",

    "content.tabs.link",

    "content.tooltips",

    # "header.autohide",

    # "navigation.expand",

    "navigation.footer",

    "navigation.indexes",

    "navigation.instant",
    "navigation.instant.prefetch",
    #"navigation.instant.progress",

    "navigation.path",

    #"navigation.prune",

    "navigation.sections",

    #"navigation.tabs",
    #"navigation.tabs.sticky",

    "navigation.top",

    "navigation.tracking",

    "search.highlight",

    # "toc.follow",

    #"toc.integrate",
]

[project.theme.icon]
#logo = "lucide/smile"
repo = "fontawesome/brands/github"

#[project.theme.font]
#text = "Inter"
#code = "Jetbrains Mono"

[[project.theme.palette]]
scheme = "default"
toggle.icon = "lucide/sun"
toggle.name = "Switch to dark mode"

[[project.theme.palette]]
scheme = "slate"
toggle.icon = "lucide/moon"
toggle.name = "Switch to light mode"

[[project.extra.social]]
icon = "fontawesome/brands/github"
link = "https://github.com/M1nu0x0/"