
name: Deploy Docs with BLUE-GREEN Deployment

on:
  push:
    paths:
      - 'docs/.vuepress/public/repos_data.json'
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # if your docs needs submodules, uncomment the following line
          # submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
          cache: npm

      - name: Install Deps
        run: npm ci

      - name: Build Docs
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          npm run docs:build
          > docs/.vuepress/dist/.nojekyll

      # Staging Deployment
      - name: Move Build to Staging
        run: mv docs/.vuepress/dist staging

      # Validate the build
      - name: Validate Staging
        run: |
          if [ -d "staging" ]; then
            echo "Staging build successful"
          else
            echo "Staging build failed"
            exit 1
          fi

      # Production Deployment
      - name: Move Build to Production
        run: |
          mv prodictoin backup || true
          mv staging production

      # Deploy to GitHub Pages
      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # This is the branch where the docs are deployed to
          branch: gh-pages
          folder: production
